core/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from core import views as core_views
from django.conf import settings
from django.conf.urls.static import static
from core.forms import ProfileRegistrationForm, LoginForm
from registration.backends.default.views import RegistrationView
from core.views import LoginView, SignupView
#from registration.backends.default.urls import url, include
from core.scrape_poly_t import setup

urlpatterns = [
    url(r'accounts/register/$',
            SignupView,
            name = 'registration_register'),
    url(r'accounts/login/$',
            LoginView,
            name = 'auth_login'),

    url(r'^accounts/', include('registration.backends.default.urls')),

    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^index/$', core_views.index, name='index'),
    url(r'^profile/$', core_views.profile_read, name='profile'),
    url(r'^profile_edit/$', core_views.profile_edit, name='profile_edit'),
    url(r'^list_of_courses/$', core_views.view_courses, name='list_of_courses'),
    url(r'^list_of_groups/$', core_views.view_groups, name='list_of_groups'),
    url(r'^group/add/$', core_views.group_create, name='group_create'),
    url(r'^group/(?P<pk>\d+)/$', core_views.view_group_information, name='group_view'),
    url(r'^group/(?P<pk>\d+)/safety_code/$', core_views.view_safety_code, name='safety_code'),
    #url(r'^group/(?P<pk>\d+)/delete/$', core_views.GroupDelete.as_view(), name='group_delete'),
    #url(r'^course/add/$', core_views.CourseCreate.as_view(), name='course_create'),
    url(r'^course/add/$', core_views.create_course, name='course_create'),
    url(r'^course/(?P<pk>\d+)/$', core_views.CourseEdit.as_view(), name='course_view'),
    url(r'^course/(?P<pk>\d+)/delete/$', core_views.CourseDelete.as_view(), name='course_delete'),
    url(r'^course/my_courses/$', core_views.view_my_courses, name='my_courses'),
    url(r'^group-autocomplete/$', core_views.GroupAutocomplete.as_view(), name='group-autocomplete'),
    url(r'^my-timetable/$', core_views.my_timetable, name='my-timetable'),
    url(r'^get_timetable/$', core_views.get_timetable, name='get_timetable'),
	#url(r'^group-autocomplete/$',core_views.GroupAutoCompleteView.as_view(), name='group-autocomplete'),
    url(r'^help_unreg/$', core_views.view_help_unreg, name='help_unreg'),
    url(r'^help_reg/$', core_views.view_help_reg, name='help_reg'),
    url(r'^admin/', admin.site.urls),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

setup()

core/models.py
from django.db import models
from django.utils import timezone
from registration.signals import user_registered
from django.contrib.auth import get_user_model
from django.contrib.auth.models import BaseUserManager
from django.contrib.auth import get_user_model

from django.contrib.auth.models import User
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import BaseUserManager
import logging

class ModelTeacher(models.Model):
    first_name = models.CharField(max_length=30)
    middle_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    degree = models.CharField(max_length=120)

    def full_name(self):
        return self.first_name + " " + self.middle_name + " " + self.last_name

class ModelGroup(models.Model):
    number = models.CharField(max_length=30)
    faculty = models.CharField(max_length=120)
    faculty_abbr = models.CharField(max_length=30)
    spec = models.CharField(max_length=120)
    def get_absolute_url(self):
        return "/group/%i/" % self.id

class ModelCourse(models.Model):
    name = models.TextField()
    teacher = models.ForeignKey(ModelTeacher, null=True)
    groups = models.ManyToManyField(ModelGroup, null=True)
    def get_absolute_url(self):
        return "/course/%i/" % self.id
    def from_model(self):
        return Course(name=self.name, teacher_name=self.teacher.name, model_groups=self.groups)


class ModelClassFormat(models.Model):
    day_of_week = models.IntegerField()
    type_of_class = models.CharField(max_length=254)
    time_of_beginning = models.TimeField()
    time_of_ending = models.TimeField()
    building = models.CharField(max_length=30)
    auditorium = models.CharField(max_length=30)
    week_number = models.IntegerField()
    course = models.ForeignKey(ModelCourse, on_delete=models.CASCADE, null=True)
    def from_model(this, c):
        return ClassFormat(day_of_week=this.day_of_week, course=c,
            type_of_class=this.type_of_class, time_of_beginning=this.time_of_beginning,
            time_of_ending=this.time_of_ending, building=this.building,
            auditorium=this.auditorium, week_number=this.week_number)


class UserProfile(models.Model):
    user = models.ForeignKey('auth.User')
    first_name = models.CharField(max_length=30)
    middle_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    phone_number = models.CharField(max_length=30)
    email = models.CharField(max_length=40)
    is_lecturer = models.BooleanField()

    degree = models.CharField(max_length=120)
    # or
    group_key = models.ForeignKey('Group', null=True)

    def full_name(self):
        return self.first_name + " " + self.middle_name + " " + self.last_name

class Subject(models.Model):
    name = models.CharField(max_length=254)
    is_necessary = models.BooleanField(default='True')

class Group(models.Model):
    starosta_id = models.OneToOneField(UserProfile, null=True)
    number = models.CharField(max_length=30)
    faculty = models.CharField(max_length=120)
    faculty_abbr = models.CharField(max_length=30)
    spec = models.CharField(max_length=120)
    def get_absolute_url(self):
        return "/group/%i/" % self.id
    def get_safety_code_url(self):
        return "/group/%i/safety_code/" % self.id

class Course(models.Model):
    name = models.CharField(max_length=254)
    report_type = models.CharField(max_length=254)
    teacher_name = models.CharField(max_length=254)
    beginning_date = models.DateField()
    ending_date = models.DateField()
    subject = models.ForeignKey(Subject)
    model_groups = models.ManyToManyField(ModelGroup)
    groups_allowed = models.ManyToManyField(Group)
    users_allowed = models.ManyToManyField(UserProfile)
    subject = models.ForeignKey('Subject')
    def get_absolute_url(self):
        return "/course/%i/" % self.id

class CommonMaterial(models.Model):
    text = models.TextField()
    subject = models.ForeignKey('Subject')

class Class(models.Model):
    conspect = models.TextField()
    homework = models.TextField()
    data = models.DateTimeField()
    is_canceled = models.BooleanField()
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

class ClassFormat(models.Model):
    day_of_week = models.IntegerField()
    type_of_class = models.CharField(max_length=254)
    time_of_beginning = models.TimeField()
    time_of_ending = models.TimeField()
    building = models.CharField(max_length=30)
    auditorium = models.CharField(max_length=30)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    week_number = models.IntegerField()

class ClassMaterial(models.Model):
    text = models.TextField()
    class_id = models.ForeignKey(Class, on_delete=models.CASCADE)

class SecretCode(models.Model):
    code = models.CharField(max_length=8)

# def user_registered_callback(sender, user, request, **kwargs):
#     profile = UserProfile(user = user)

#     profile.is_lecturer = bool(request.POST["is_lecturer"])
#     profile.first_name = request.POST["first_name"]
#     profile.middle_name = request.POST["middle_name"]
#     profile.last_name = request.POST["last_name"]
#     profile.phone_number = request.POST["phone_number"]
#     profile.email = request.POST["email"]
#     profile.degree = request.POST["degree"]

#     group = Group(number = "100/1")
#     group.starosta_id = profile
#     group.save()

#     profile.save()

# user_registered.connect(user_registered_callback)

# @receiver(post_save, sender=Course)
# def post_save_course_ds(sender,instance, **kwargs):
#     if (use)
#     instance.faculty

class EmailBackend(object):
    def authenticate(self, username=None, password=None, **kwargs):
        logger.error('Something wrong in authentificate!')

        UserModel = get_user_model()
        try:
            user = UserModel.objects.get(email=username)
        except UserModel.DoesNotExist:
            return None
        else:
            if user.check_password(password):
                return user
        return None

templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Main{% endblock %}</title>
  {% load static %}
 <meta name="viewport" content="width=device-width, initial-scale=1">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   <!-- Bootstrap -->

    <link href={% static "css/bootstrap.min.css" %} rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

<style>
.help_st {
    padding-left: 100px;
    padding-right: 100px;
}

.bg-4 {
    background-color: #00ff00;
    color: #0000ff;
}

.help_link {
    font-size: 120%;
    display: inline-block;
   }

   .regist {
       padding-right: 100px;
      }

</style>

   <!-- Bootstrap -->
    <link href={% static "css/bootstrap.min.css" %} rel="stylesheet">
</head>


<body>
  <header>
     <div class="container-fluid text-left">
     <div class="row">

       <div class="col-sm-5 font-color:#ffffff" >
         <p  style="color:white">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
       </div>

         <div class="col-sm-2" >
           <h1><a href="{% url 'home' %}"><img src="{% static "gdepara.jpg" %}"/><br>Где пара?</a></h1>
         </div>


        {% if user.is_authenticated %}
        <div class="col-sm-1" style="padding-top: 70px">
          <a class="btn btn-success" href="{% url 'my-timetable' %}" role=button>Расписание</a>
        </div>
        <div class="col-sm-1" style="padding-top: 70px">
          <div class="container-fluid text-right">
             <a class="btn btn-primary" href="{% url 'help_reg' %}" role=button>Помощь</a>
           </div>
        </div>
        <div class="col-sm-1" style="padding-top: 70px">
          <div class="container-fluid text-left">
            <a class="btn btn-danger" href="{% url 'auth_logout' %}" role=button>Выход</a>
          </div>
        </div>
        {% else %}
        <div class="col-sm-3" style="padding-top: 70px">
            <a class="btn btn-primary" href="{% url 'help_unreg' %}" role=button>Помощь</a>
        </div>
        {% endif %}

    </div>
    <div class="form-group">
    <div class="container">
    <div class="row">
    <form role="search">
    <div class="input-group">
    <input name="number" id="number" class="form-control" placeholder="Введите номер группы">
    <span class="input-group-btn">
    <button class="btn btn-success" name="search_b" id="search_b" type="button">
    <i class="glyphicon glyphicon-search"></i>
    </button>
    </span>
    </div>
    </form>
    </div>
    </div>
    </div>
    <script>
        var csrf_token = '{% csrf_token %}';
        $("#search_b").click( function() {
            alert()
            });
    </script>

    <script type="text/javascript">
    $(function() {
    $("#number").autocomplete({
    source: "/autocomplete/group/",
    minLength: 2,
    });
    });
    </script>



  </header>

  <hr>
  <main>
  <div class="container-fluid bg-1 text-center">
    {% block content %}
    {% endblock %}
  </div>
  </main>
  <!-- hr -->
	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
</body>
</html>

templates/create_course.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>
{% endblock %}

templates/group_form.html
{% extends 'base.html' %}

{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Добавить">
<!doctype html>
<html lang="en">
</html>
</form>

{% endblock %}

templates/group_info.html
{% extends 'base.html' %}

{% block content %}
  <h2>Группа {{group.number}}</h2>
  <form method="post">
    {% csrf_token %}
    <p>Список группы:</p>
    {% for c in group_list %}
    {% if c.id == group.starosta_id.id %}
    <div>
      <p>{{c.first_name}}
      {{c.middle_name}}
      {{c.last_name}} 
      (Староста)</p>
    </div>
    {% else %}
    <div>
      <p>{{c.first_name}}
      {{c.middle_name}}
      {{c.last_name}}</p>
    </div>
    {% endif %}
    {% endfor %}

  {% if code %}
  <p>Пригласительный код: {{code}}</p>
  {% endif %}

  {% if user.group_key == group %}
    <button type="submit">Покинуть группу</button>
    <input type="submit" id="buttonId" name="generate_code" value="Сгенерировать пригласительный код">
  {% endif %}

  {% if not user.group_key %}
    <a href="{{group.get_safety_code_url}}">Присоединиться к группе</a>
  {% endif %}
  <button type="button" class="btn btn-xl" onclick="javascript:history.go(-1);">Назад</button>
  </form>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
      <h2> Здравствуйте, {{ user.first_name }}! </h2><br>
      <a class="btn btn-success" href="{% url 'profile' %}" role=button>Просмотр профиля</a>
    {% else %}
      <a class="btn btn-success" href="{% url 'auth_login' %}" role=button>Войти</a>
      <a class="btn btn-success" href="{% url 'registration_register' %}" role=button>Зарегистрироваться</a>
    {% endif %}
{% endblock %}

templates/list_of_courses.html
{% extends 'base.html' %}

{% block content %}
  <h2>List of Courses</h2>
  <form method="post">
    {% csrf_token %}
    {% for c in courses %}
    <div>
		<a href="{{c.get_absolute_url}}">{{c.name}}</a>
		{% if c in user.course_set.all %}
			(В моём списке)
		{% else %}
			<input type="submit" id="buttonId" name="{{c.name}}" value="Присоединиться к курсу">
		{% endif %}
    </div>
    {% endfor %}
  <p><a href="{% url 'course_create' %}">создать курс</a></p>
  <button type="button" onclick="location.href='{% url 'my_courses' %}'">Назад</button>
  </form>
{% endblock %}

templates/list_of_groups.html
{% extends 'base.html' %}

{% block content %}
  <h2>Список групп</h2>
    {% csrf_token %}
    {% for c in groups %}
    <div>
		<a href="{{c.get_absolute_url}}">{{c.number}}</a>
    </div>
    {% endfor %}
  {% if not user.group_key %}
    <p><a href="{% url 'group_create' %}">Создать группу</a></p>
  {% endif %}
  <button type="button" class="btn btn-success" onclick="javascript:history.go(-1);">Назад</button>
  
{% endblock %}

templates/logged_out.html
{% extends 'base.html' %}

{% block title %}See you!{% endblock %}

{% block content %}
  <h2>Logged out</h2>
  <p>You have been successfully logged out.</p>
  <p><a href="{% url 'login' %}">Log in</a> again.</p>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block title %}Вход в систему{% endblock %}


{% block content %}
<div class="container-fluid text-right" style = "padding-bottom: 20px">
<div class="row content">
    <div class="col-sm-2" >
    </div>


    <div class="col-sm-6" >
      <h2>Введите учетные данные</h2>
      <form method="post">
      {% if error %}<p style="color:red"><strong>Неверный логин или пароль</strong></p>{% endif %}
        {% csrf_token %}
        {{ form.as_p }}
      <button class="btn btn-success" type="submit">Войти</button>

      <button class="btn btn-success" type="button" onclick="javascript:history.go(-1);">Отмена</button>
      </form>
    </div>

    <div class="col-sm-3 font-color:#ffffff" >
      <p  style="color:white">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    </div>
</div>
</div>

{% endblock %}

templates/profile_edit.html
{% extends 'base.html' %}

{% block content %}
<h2>Изменить информацию профиля</h2>
<div class="container-fluid text-right">
<div class="row content">
  <div class="col-sm-4 font-color:#ffffff" >
    <p  style="color:white">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>


    <div class="col-sm-4" >

      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
      <button class="btn btn-success" type="submit">Сохранить</button>
      <!--a class="btn btn-success" type="submit">Сохранить</a!-->
      <button class="btn btn-success" type="button" class="btn btn-xl" onclick="javascript:history.go(-1);">Отмена</button>
      </form>
    </div>

    <div class="col-sm-4 font-color:#ffffff" >
      <p  style="color:white">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    </div>
</div>
</div>














{% endblock %}

templates/profile_read.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid text-left">
<div class="row content">
  <div class="col-sm-4 font-color:#ffffff" >
    <p  style="color:white">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>


    <div class="col-sm-4" >
      <h2>Мой профиль</h2>
      {% if user.is_lecturer == True %}<p>Преподаватель</p> {% else %} <p>Студент</p>{% endif %}
        <p>Почта: {{user.email}}</p>
        <p>Имя: {{user.first_name}} {{user.middle_name}} {{user.last_name}}</p>
        <p>Телефон: {{user.phone_number}}</p>
        {% if not user.is_lecturer %}
            {% if not user.group_key %}

                <form method="POST">
                <select name="select_gr">
                {% for g in grs %}
                    <option value="{{ g.number }}">{{ g.number }}</option>
                {% endfor %}
                </select>
                <button id="create_group" type="button">Создать группу </button>
                </form>
            {% else %}
                {% if user.group_key.starosta_id.id == user.id %}
                    <p>Группа:
                    <a href="{{user.group_key.get_absolute_url}}">{{user.group_key.number}} (Староста)</a>
                    </p>
                {% else %}
                    <p>Группа:
                    <a href="{{user.group_key.get_absolute_url}}">{{user.group_key.number}}</a>
                    user
                    </p>
                {% endif %}

                <button id="myClickButton" type="button">Отсоединиться от группы:</button>
            {% endif %}
        {% endif %}
        <script>
            var csrf_token = '{% csrf_token %}';
            $("#create_gr").click( function() {
                alert($("#select_gr").val())
                $.post("create_group", {'group' : $("#select_gr").val()}, function (data) {
                    alert(data)
                });
            });
        </script>
        <a class="btn btn-success" onclick="location.href='{% url 'profile_edit' %}'">Редактировать</a>
        <a class="btn btn-success" onclick="location.href='{% url 'my_courses' %}'">Мои курсы</a>
        <a class="btn btn-success" onclick="location.href='{% url 'list_of_groups' %}'">Список групп</a>
    </div>

    <div class="col-sm-4 font-color:#ffffff" >
      <p  style="color:white">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    </div>
</div>
</div>
{% endblock %}

templates/safety_code.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid text-right">
  <form method="post">
    {% csrf_token %}
    {% if wrong %}
    <p>Неверный код!!!</p>
    {% endif %}
    {{ form.as_p }}
    <input type="submit" value="Ввести">
  <button type="button" class="btn btn-xl" onclick="javascript:history.go(-1);">Назад</button>
  </form>
</div>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block title %}Регистрация{% endblock %}

{% block content %}
<div class="container-fluid text-right" style = "padding-bottom: 20px">
<div class="row content">
    <div class="col-sm-2" >
    </div>


    <div class="col-sm-6" >
      <h2>Введите данные учетной записи</h2>
      <form method="post">
      {% if error %}<p><strong>Пользователь с таким адресом электронной почты уже зарегистрирован</strong></p>{% endif %}
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-success" type="submit">Зарегистрироваться</button>
      <button class="btn btn-success" type="button" onclick="javascript:history.go(-1);">Отмена</button>
      </form>
    </div>

    <div class="col-sm-3 font-color:#ffffff" >
      <p  style="color:white">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    </div>
</div>
</div>
{% endblock %}

templates/timetable.html
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Main{% endblock %}</title>
  {% load static %}
  
   <!-- Bootstrap -->
  <link href={% static "css/bootstrap.min.css" %} rel="stylesheet">
  
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet" />
  <link href="https://cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/e8bddc60e73c1ec2475f827be36e1957af72e2ea/build/css/bootstrap-datetimepicker.css" rel="stylesheet" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.js"></script>
  <script src="https://cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/e8bddc60e73c1ec2475f827be36e1957af72e2ea/src/js/bootstrap-datetimepicker.js"></script>
  <script src='{% static "js/timetable.js" %}'></script>
</head>
<body>
<header>
  <h1><a href="{% url 'home' %}"><img src="{% static "gdepara.jpg" %}"/><br>Где пара</a></h1>
  <h1><a href="{% url 'my-timetable' %}"><br>Расписание</a></h1>
  {{ testme }}
</header>
<div id="left" width='50%'>
  <div class="col-lg-6 datepicker_area" style="background: white;">
    <div style="overflow:hidden;">
      <div class="form-group">
        <div class="row">
          <div class="col-md-12">
            <div id="datetimepicker" data-date="03/12/2012"></div>
            <input type="hidden" name="date" id="my_hidden_input" value="">
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-4 col-md-offset-1" id="day-content">
  </div>
  <table class="table table-bordered" id="day-content-item" style="display:none">
    <thead>
    <tr class="success"> <th colspan="2" class="item-title">title</th></tr>
    </thead>
    <tbody>
    <tr>
      <td class="item-start">11</td>
      <td class="item-teacher">12</td>
    </tr>
    <tr>
      <td class="item-end">21</td>
      <td class="item-cabinet">22</td>
    </tr>
    </tbody>
  </table>
</div>

</body>
</html>